# Generated by Django 2.1.2 on 2019-07-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0003_auto_20160530_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastpokemontype', to='pokemon_v2.Generation')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastpokemontype', to='pokemon_v2.Pokemon')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastpokemontype', to='pokemon_v2.Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
