# Generated by Django 2.1.2 on 2019-12-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0004_auto_typeefficacypast'),
        ('pokemon_v2', '0004_pokemontypepast'),
    ]

    operations = [
    ]
