# Generated by Django 2.1.11 on 2020-04-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0005_pokemonformtype'),
        ('pokemon_v2', '0005_pokemontypepast_typeefficacypast'),
    ]

    operations = [
    ]
